default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template1

development:
  <<: *default
  database: checkmywork_development

test:
  <<: *default
  database: checkmywork_test

production:
  <<: *default
  database: checkmywork_production
  username: checkmywork
  password: <%= ENV['CHECKMYWORK_DATABASE_PASSWORD'] %>
